# Generated by Django 2.2.7 on 2019-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('job_id', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('commission_pct', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('manager_id', models.IntegerField(null=True)),
                ('department_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
